id: P826AC407
initial_creation_type: input
source_metadata:
  Title: Kāśyapaparivarta-nāma-mahāyāna-sūtra
  Editor: Stael-Holstein, Baron A.Von.
  Publisher: '-'
  Place of Publication: Shanghai, China
  Year: '1925'
  Kāśyapaparivarta sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:03:56.220275'
last_modified_at: '2022-03-08T16:03:56.220284'
